name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request: {}
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: "true"
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Start containers
      run: docker compose up -d --build
      working-directory: playwright-docker

    - name: Install dependencies
      run: npm ci
    - name: Run Playwright tests
      run: npx playwright test

    - name: Stop containers
      if: always()
      working-directory: playwright-docker
      run: docker compose down

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
